name = "TimeSeriesTools"
uuid = "91134f95-7454-4862-8ff6-d8ca75e2e70d"
authors = ["John Waczak <john.louis.waczak@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
